### ISSUE TITLE
Making xwmt and xwmb conventions consistent.

### ISSUE THREAD

**Issue by hdrake** [hdrake/xwmb#2]
We need to think a bit more carefully about coordinate naming conventions for `xwmb` than for `xwmt`. First of all, we use variables on all four different C-grid grids (suffix `h` or `t` for tracers, `u` for zonal velocity, `v` for meridional velocity, and `c` or `q` for tracer cell corners, or vorticity). This is further complicated because we also need to pass datasets to `sectionate`, which has its own requirements for coordinate conventions.

I think the more straight forward approach is to following the default MOM6 grid suffix conventions:
-`(xh,yh)` for tracer cells centers
- `(xq, yq)` for tracer cell corners (or center of vorticity cells)
- `(xq, yh)` for center of zonal velocity faces
- `(xh, yq)` for center of meridional velocity faces

I think all this would mean is changing all of the `x` and `y` in `xwmt` to `xh` and `yh`.

What do you think, @gmacgilchrist and @jetesdal?

**Comment by aradhakrishnanGFDL** [comment]
Sorry, I missed this. The [CMIP6 grids table](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_grids.json) may be useful for this discussion. CMOR specific questions/issues can go [here](https://github.com/PCMDI/cmor).

**Comment by hdrake** [comment]
This issue is side-stepped by inferring dimensions from `xgcm.Grid.axis` metadata.
