### ISSUE TITLE
Provide diag_table

### ISSUE THREAD

**Issue by cspencerjones** [hdrake/xwmb#8]
We would love to be able to adapt the example to work with our own model output (I have run a couple of years of OM4_025.JRA and can run more with different diagnostics). It would really help if we could see your diag_table file. Is that possible? 

Thanks for this package.

**Comment by hdrake** [comment]
Sure thing. This should contain everything you'll need: 
https://github.com/hdrake/xwmb/blob/6cc8f0c4486fc826bd4ec760957b4364445e7baa/examples/MOM6_diagtable

I've had best results with output on the native grid, but you could use `rho2` or `zstr` instead, depending on your application.

You can also work through the example notebooks here and in `xwmt` with the test data here: https://github.com/hdrake/xwmt/blob/84a0baeb775eefd44cd9ef6c02f25f30b5073559/xwmt/tests/conftest.py#L9-L13
